name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  # Run full test suite before release
  test:
    name: Full Test Suite
    uses: ./.github/workflows/test.yml

  # Run code quality checks before release
  quality:
    name: Code Quality Checks
    uses: ./.github/workflows/quality.yml

  # Create GitHub release
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [test, quality]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: '.go-version'

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.3.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            # Caddy CertStore ${{ steps.get_version.outputs.VERSION }}

            A Caddy v2 module for loading TLS certificates from OS certificate stores (macOS Keychain, Windows Certificate Store).

            ## Changes

            ${{ steps.changelog.outputs.changelog }}

            ## Installation

            ```bash
            xcaddy build --with github.com/hurricanehrndz/caddy-certstore@${{ steps.get_version.outputs.VERSION }}
            ```

            ## Documentation

            See [README.md](https://github.com/${{ github.repository }}/blob/${{ steps.get_version.outputs.VERSION }}/README.md) for usage instructions.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
